# The path to listen for GitHub POSTs on
path: /
port: 8008
secret: GitHubWebhookVerificationSecret
# Available variables:
#   $REPO_NAME:  Name of repository.
#   $REPO_OWNER: The owner of the repository.
#   $BRANCH:     The name of the branch.
pull-directory: /srv/$REPO_NAME/$BRANCH
